- name: variables
  hosts: local
  connection: local
  vars:
    course: "devops with AWS"
    duration: "120 hrs"
  tasks:
  - name: print the var1
    vars:
      course: "Ansible"
    ansible.builtin.debug:
      msg: "Course is {{course}} and Duration is {{duration}}"

  - name: print the var2
    vars:
      course: "Shell"
      duration: "1 week"
    ansible.builtin.debug:
      msg: "Course is {{course}} and Duration is {{duration}}"

  - name: print the var3
    ansible.builtin.debug:
      msg: "Course is {{course}} and Duration is {{duration}}"