- name: variables
  hosts: local
  connection: local
  vars_files:
  - course.yaml
 
  tasks:
  - name: print the var1
    vars:
      course: "Shell"
      duration: "1 week"
    ansible.builtin.debug:
      msg: "Course is {{course}} and Duration is {{duration}}"

  - name: print the var2
    ansible.builtin.debug:
      msg: "Course is {{course}} and Duration is {{duration}}"