- name: variables
  hosts: web
  vars:
    course: "devops with AWS"
    duration: "120 hrs"
  tasks:
  - name: print the variable
    ansible.builtin.debug:
      msg: "Course is {{course}} and Duration is {{duration}}"