- name: variables with preference
  hosts: local
  connection: local
  vars: # play level
    Harsha: Play
  tasks:
  - name: from play 1
    ansible.builtin.debug:
      msg: "Hello from {{ Harsha }}"
