- name: filters
  hosts: local
  connection: local
  tasks:
  - name: handle undefine variable
    ansible.builtin.debug:
      msg: "Hello {{ person | default('Ramesh') }}"

  - name: convert string to list
    vars:
      fruits: "apple, banana, orange" #String
    ansible.builtin.debug:
      msg: "Fruits are: {{ fruits | split(',') }}"

  - name: check ipaddress is valid or not
    vars:
      ip: "192.168.1.1.89"
    ansible.builtin.debug:
      msg: "{{ ip | ansible.utils.ipaddr }}"