- name: shell vs command
  hosts: local
  connection: local
  tasks:
  - name: executive command
    #ansible.builtin.command: ls -ltr > /tmp/output.txt # it cannot be executed
    ansible.builtin.shell: ls -ltr > /tmp/output.txt # it will execute

  - name: executive command
    #ansible.builtin.command: ls 
    ansible.builtin.command: ls -a
    register: command_res

  - name: read command output
    ansible.builtin.debug:
      msg: "{{ command_res }}"


